#!/usr/bin/env node

console.log(process.argv);

var celsius = false;
var ferinheight = false;
var location = null;

each(process.argv.slice(2), function(arg) {
  switch (arg) {
    case '-h':
    case '--help':
      console.log("Here's some help...");
      process.exit(0);
      break;
    case '-V':
    case '--version':
      console.log('weather 0.1.0');
      process.exit(0);
      break;
    case '-f':
    case '--ferinheight':
      ferinheight = true;
      break;
    case '-c':
    case '--celsius':
      celsius = true;
      break;
    default:
      location = arg;
      break;
  }
});

if (!celsius && !ferinheight) {
  ferinheight = true;
}

if (!location) {
  location = 'Portland, OR';
}

console.log('The weather in %s is hopefully sunny.', location);
if (ferinheight) {
  console.log('The temperature is 70 Ferinheight.');
}
if (celsius) {
  console.log('The temperature is 21 Celsius.')
}