#!/usr/bin/env node


/**
 * Module dependencies.
 */

console.log(process.argv);
var program = require('commander');
var calculations = require('./calculations.js');

program
  .version('0.0.1')
  .option('-a, --add', 'add')
  .option('-s, --sub', 'subtract')
  .option('-m, --mult', 'multiply')
  .parse(process.argv);

var num1 = (parseInt(program.args[0]));
var num2 = (parseInt(program.args[1]));

if(program.add) {
	_ = calculations.add(num1, num2);
	console.log(num1 + ' + ' + num2 + ' is ' + _ + '.');

}

if(program.sub) {
	_ = calculations.sub(num1, num2);
	console.log(num1 + ' - ' + num2 + ' is ' + _ + '.');

}

if(program.mult) {
	_ = calculations.mult(num1, num2);
	console.log(num1 + ' * ' + num2 + ' is ' + _ + '.');

}
