#!/usr/bin/env node

// // console.log(process.argv);

// var calculations = require('./calculations.js');

// console.log('The sum is ' + sum)


/**
 * Module dependencies.
 */

console.log(process.argv);
var program = require('commander');
var calculations = require('./calculations.js');

program
  .version('0.0.1')
  .option('-a, --add', 'add')
  .option('-s, --subtract', 'subtract')
  .parse(process.argv);

if(program.add) {

	var num1 = (parseInt(program.args[0]));
	var num2 = (parseInt(program.args[1]));
	// var num = parseInt[num1, num2];
	sum = calculations.add(num1, num2);


	var sum = calculations.add(num1, num2);
	
}

console.log(program.args[0] + ' + ' + program.args[1] + ' is ' + sum + '.');
